---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app teslamate
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      teslamate:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17@sha256:a9f405688344a8a6f718e2c344438342ad21540986aeb5ab5fa781831eb2c597
            envFrom: &envFrom
              - secretRef:
                  name: teslamate-secret
        containers:
          app:
            image:
              repository: teslamate/teslamate
              tag: "1.32.0"

            envFrom: *envFrom

            env:
              TZ: ${TZ}
              DISABLE_MQTT: "false"
              MQTT_HOST: "emqx-listeners.dbms.svc.cluster.local"
              DATABASE_NAME: "teslamate"
              DATABASE_HOST: "postgres17-rw.dbms.svc.cluster.local"

            resources:
              requests:
                memory: 250Mi
                cpu: 50m
              limits:
                memory: 500Mi

    service:
      app:
        controller: teslamate
        ports:
          http:
            port: 4000

    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: teslamate.png
          gethomepage.dev/name: TeslaMate
          gethomepage.dev/group: Home
        hosts:
          - host: &host teslamate.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
