---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wizarr
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      wizarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository:  ghcr.io/wizarrrr/wizarr
              tag: 4.2.0
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 15m
                memory: 180M
              limits:
                memory: 300M
    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 568
    #     runAsGroup: 568
    #     fsGroup: 568
    #     fsGroupChangePolicy: OnRootMismatch
    #     seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5690
    ingress:
      app:
        className: external
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/name: Wizarr
          gethomepage.dev/icon: wizarr.png
          gethomepage.dev/description: Plex Invite Management
          # gethomepage.dev/widget.type: wizarr
          # gethomepage.dev/widget.url: http://wizarr.self-hosted.svc.cluster.local:5690
          # gethomepage.dev/widget.key: ${WIZARR_TOKEN}
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          authelia.enabled: "true"
        hosts:
          - host: onboard.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /data/database
