---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app hoarder
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"

    controllers:
      hoarder:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/hoarder-app/hoarder
              tag: 0.22.0@sha256:e2156f3de4a1eafc53afb6e682f20857be4449d7e9d24240afe6d9ccd280ed3b
            env:
              BROWSER_WEB_URL: http://hoarder-chrome.services.svc.cluster.local:9222
              CRAWLER_DOWNLOAD_BANNER_IMAGE: true
              CRAWLER_ENABLE_ADBLOCKER: true
              CRAWLER_STORE_SCREENSHOT: true
              DATA_DIR: /data
              # DISABLE_SIGNUPS: true
              DISABLE_NEW_RELEASE_CHECK: true
              NEXTAUTH_URL: https://hoarder.${SECRET_DOMAIN}
              MEILI_ADDR: http://hoarder-meilisearch.services.svc.cluster.local:7700
              NEXTAUTH_URL_INTERNAL: http://hoarder-app.services.svc.cluster.local:3000
              OAUTH_PROVIDER_NAME: Authelia
              OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"
              DISABLE_PASSWORD_AUTH: "true"
            envFrom: &envFrom
              - secretRef:
                  name: hoarder-secret

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

      chrome:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
            args:
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
            securityContext:
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

      ## TO-DO: fix meilisearch crash
      meilisearch:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - hoarder

        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.12.7
            env:
              MEILI_NO_ANALYTICS: true
            envFrom: *envFrom
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi

    service:
      app:
        controller: hoarder
        ports:
          http:
            port: 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700

    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Hoarder
          gethomepage.dev/description: The Bookmark Everything app
          gethomepage.dev/group: Services
          gethomepage.dev/icon: https://media.invisioncic.com/u329766/monthly_2024_05/hoarder.png.cb75b7347d47989bd0c3e65b9e613700.png
          gethomepage.dev/pod-selector: >-
            app.kubernetes.io/name in (hoarder)
        hosts:
          - host: &host hoarder.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          hoarder:
            app:
              - path: /data
                subPath: hoarder
          meilisearch:
            app:
              - path: /meili_data
                subPath: meilisearch
