---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-mgmt
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-mgmt",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.1",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "10.90.0.0/16"}
            ]
          }
        }
      ]
    }
