apiVersion: v1
kind: Secret
metadata:
  name: postgres
stringData:
  POSTGRES_SUPER_USER: ENC[AES256_GCM,data:zY13lvXEHi4=,iv:IpzEH8GInM0kKRkYTgvV8OS1iW1RaVbXS4+wBeNWGRM=,tag:qNq+lrhPoXuCrA0T6GZVQA==,type:str]
  POSTGRES_SUPER_PASSWORD: ENC[AES256_GCM,data:DWCO0ft8thyGYJua4cvufGV4ZElZwgJf/Z2pcAM1S2SvUUzttYIseWn8n7/Qg88=,iv:tXh2erKuRsLPGSPQ5tfpvzPu9YFCzvNef9Kx1wtt1Gs=,tag:Oyhh4NGAwwbcbucX/P4pVw==,type:str]
  username: ENC[AES256_GCM,data:ofIqF369Zug=,iv:KzxYZcQBzqIvB7yoRxjtHMalyCzYSkimk8Kp9sQp4Rw=,tag:Ok0g/Gzyr/LkhcWjqO7JpQ==,type:str]
  password: ENC[AES256_GCM,data:C0OYxNfepDpsfC550wr7cWgR/TS8QKruqVmduCkGynLhOi/npDIZxCMGy7vDsMU=,iv:/e7KZXUDqZrYCxvmlBV4PjU/5D6i5WfcZj5u9jYhOJA=,tag:1zpuTibcdLgJR9UT5LJXTQ==,type:str]
  #ENC[AES256_GCM,data:y9WP1+owmnqhDJ8=,iv:cjIujX3u0ccydvjGEmmul+1Yxg5NSJtO9tfh+hxOH5A=,tag:9a+binOCHcB0BBl2rwXN+g==,type:comment]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:yMFnuc8H9ZujutU8qpobhJk4,iv:B4pns/kMYNSOmf6MisnIZVoI4Zl3+EEe9FnhcFkS/vs=,tag:PJMZAJMDPoU3mNVD6qHo0w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u7jPjMhlEPhJtrL0mK70ml1zOLVcBw==,iv:vxT+uX01ruBq6FsVvV5cdSge6BGePNGYelRc8QaOwSQ=,tag:qbVTlHQM2awHcr7tLFkGZA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZ2c5b0pTMnU0cXR2ZUZY
        Q2lLZDE3T2k0OVpjU1E4Qkw2TUVWUUtac0JBCkVCZTB1b0tENFpCb2tJcWptUkJw
        K0dvWnhCSFp1cmpUNG9BQ1hGeE16L0UKLS0tIEpkMXdZY2hLazd6NGwzUGhTYlBG
        Z3VtYm9aYlRnVHV1MFpMVnB5TEMxaHcKh7bLYXjetvVETzFy91GoqFaCVdyMZowy
        j1QeO71fz1R0RTfj5hSQYhkcLc49E6jyqCqvlMqMNdzFpqD8LucPWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-14T17:14:39Z"
  mac: ENC[AES256_GCM,data:8FIRijwU71FNX0wKsWufvJK6Nr83wBIGwat8l9oNlYBwu7A5GYeTstEzAmbTFcTDIjO3u9A0R2ToDlqX3qrbQ0LmOwHD3BESpJQjEE3f146bRNPuXeu93uAk/5sqBaPI5GrToQkEF9t9HdoOrLjFmEA8VpSRa0C55jjnf6+AmSo=,iv:NnfDwUtyJnAt2SgbTtN8hqxRpEtgqTXikqcCep/ZtTY=,tag:SlRiHsA5tXdZ1uxvMLTzkQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
