---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gramps
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      gramps:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17@sha256:a9f405688344a8a6f718e2c344438342ad21540986aeb5ab5fa781831eb2c597
            envFrom: &envFrom
              - secretRef:
                  name: gramps-secret
        containers:
          app:
            image:
              repository: ghcr.io/gramps-project/grampsweb
              tag: v25.3.1
            env:
              GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
              GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://dragonfly.dbms.svc.cluster.local:6379"
              GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://dragonfly.dbms.svc.cluster.local:6379"
              GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://dragonfly.dbms.svc.cluster.local:6379
            envFrom: *envFrom
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi

    service:
      app:
        controller: gramps
        ports:
          http:
            port: 5000

    ingress:
      app:
        className: internal
        hosts:
          - host: &host gramps.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      app:
        existingClaim: *app
        globalMounts:
          - path: /app/users
            subPath: gramps_users
          - path: /app/indexdir
            subPath: gramps_index
          - path: /app/thumbnail_cache
            subPath: gramps_thumb_cache
          - path: /app/cache
            subPath: gramps_cache
          - path: /app/secret
            subPath: gramps_secret
          - path: /app/media
            subPath: gramps_media
          - path: /tmp
            subPath: gramps_tmp
          - path: /root/.gramps/grampsdb
            subPath: gramps_db
