global:
  slack_api_url_file: /etc/secret/slack_api_url

receivers:
  - name: "null"
  - name: "slack"
    slack_configs:
      - send_resolved: true
        api_url_file: /etc/secret/slack_api_url
        text: |-
          "{{ range .Alerts }}{{ .Annotations.description }}{{ end }}"

route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 6h
  receiver: "slack"
  routes:
    - receiver: "null"
      matchers:
        - alertname =~ "InfoInhibitor|Watchdog"
    - receiver: "slack"
      matchers:
        - severity = critical
      continue: true

inhibit_rules:
  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ["alertname", "namespace"]
