---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
components:
  - ../../flux/components/common
resources: []
  # - ./docmost/ks.yaml
  # - ./actual/ks.yaml
  # - ./hoarder/ks.yaml
  # - ./it-tools/ks.yaml
  # - ./overseerr/ks.yaml
  # - ./wizarr/ks.yaml
  # - ./mealie/ks.yaml
  # - ./netboot/ks.yaml
  # - ./searxng/ks.yaml
