---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homebridge
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1000
    #     runAsGroup: 1000
    #     fsGroup: 1000
    #     fsGroupChangePolicy: OnRootMismatch

    controllers:
      homebridge:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.0.101.13/24"],
                "mac": "64:16:7f:e2:d3:0a"
              }]

        containers:
          app:
            image:
              repository: ghcr.io/homebridge/homebridge
              tag: "2025-02-16"
            env:
              TZ: ${TZ}
              ENABLE_AVAHI: 1
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8581

    ingress:
      app:
        className: internal
        hosts:
          - host: &host homebridge.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /homebridge
