---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nebula-sync
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      orbital-sync:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/lovelaze/nebula-sync
              tag: v0.7.0
            env:
              FULL_SYNC: "true"
              RUN_GRAVITY: "true"
              CRON: 0/15 * * * *
              VERBOSE: "true"
            envFrom:
              - secretRef:
                  name: nebula-sync-secret
            resources:
              requests:
                memory: 250Mi
                cpu: 50m
              limits:
                memory: 500Mi
