apiVersion: v1
kind: Secret
metadata:
    name: nebula-sync-secret
stringData:
    #ENC[AES256_GCM,data:Np9WnKqbRXMnRw==,iv:tlvoSubJJVf1yn3PZ+buKw6VmoOJS/rXhWwtlcM7fVU=,tag:klNFmFAwsiEKlkOlsBfSJw==,type:comment]
    PRIMARY: ENC[AES256_GCM,data:fRmdKKaNn42ax8NnSeIeaZkepPTFtHovKa9G1M3TYxj2lvCOxA4glsI6/KTXKqKsyTwDx+oKJdcpcHs3Xw==,iv:tase4qEQP4gc1AyqJ36O1jL8mENpkJW10JbOpVTMxqk=,tag:D+xHh7l2lqS3MG3d9QFW4w==,type:str]
    REPLICAS: ENC[AES256_GCM,data:qWxMgQCMyfni7EEmu75KesaXH+xsUEmsd09Is4yKiev1T92KyC4heYfL0IIkRQM9FAbbMWQN6PVvrDcymQ==,iv:qCNrCHLZ0ITHlA+JRC7lfuQb0MJryOFpcdvzWLy0Iic=,tag:AsD2a9eP3r++nYWkUPWruw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza2FRcEtoMVNCelJZK3ZC
            Tm9nT2JvU0dPSDcxOGxmRXUxY0hPb0NQUDE0CkJLTnRMS3dkRUx3UXhsVG9GZ0lo
            ZUZUVHBHVGNxUnNDaFpGSzNsWjBxUmMKLS0tIEZLNU44QlJJZmg5ZUVyRlFzOHFi
            R1EvM1diaWJjZWtiQjJxWFBUNE02T1UKPn/OG0a27rYh/otxheUK8RVWuU0ije/7
            ktdSvBSfVBxmri63Koz630zDrqGbW9auiv4wHTZpqjDAB/yNs20uaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-22T05:27:14Z"
    mac: ENC[AES256_GCM,data:ILIoRujIsmldDdI9iMqq6tfzgSXjwKF0qgBA4F5jqVmXgI1hXfVZ/bFCylz/2o5p0R9yzsz0HZIFOIixWQvZ45rrkb15mYu/NJ4XuRUuo/ahNWhj2ZkuDp1AxIJz6UqInthMnhUnX8qgKhbb3jqvtn8BJ0neeQbNyYVMB/HwSTw=,iv:KgwSt/0802jqjqTu+0elGsxbbs/AU34YHazwJ9f17yI=,tag:WREU21/DO4Rf7onzaaFJwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
