apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6UAYK3+PLiTYO5n2fFl+zUMt,iv:ed2RiugaDf7y6Rk5eBhmWK3gN8InyyQGl34gppgNclU=,tag:xExF6m4szZyfmCFpMUdZ9A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OKC43HbDI1RfMVIVzNCtgaV/byZdbg==,iv:gxeikpa9uIcNxgl65y5fXqbS/S9RTslrMzXNhB6t/cA=,tag:IZ/CiNKWbkjjt4g0clj8Bg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TWNpMC9nY3FwcmNwQ1JC
        a3RPeHVmQ0h6cWw5RlYrNm9WUlBpYnFRQnpvCisrZDVCZ2p2UHcxVDRrWktENG5J
        VDNHM01VcHFvc0NXeWhwQjVNZmhwbTgKLS0tIEx5REZIcy8rc2k2QzM1TVZ2RjZn
        QWh3M0d0dVovL0paQlVhN1VDbm5RS0EK9FO78k6o00O81yvP9NFO8HTviyu1eLdt
        NGP1iAYcpk5aDcukRlTvfCBZgEddWfEXw46VSLna1eC6jdSWg+lCGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-14T17:14:39Z"
  mac: ENC[AES256_GCM,data:+l1RIjPlcwYv7bkwPHcF8s+4UbVq/UWCb89z6PML2w5NmJY9SdHYduosoZ2qUF2nUSXjSDUJowNV5JFoOliLojGc58XSzIGYjwBfN5gnQt2euOcLmtipFQ5ksNPI2IzB1x1rkKDNYXqqixC/17iYqUem8YURxf3BVX68sz2Wqk8=,iv:9PBEtha03dU0224+IdPnlxcRr6AdyrUcETfwTfyS+rM=,tag:BgZh0ojG5YugQXWWVBnQnw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
