apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
stringData:
    UNIFI_HOST: ENC[AES256_GCM,data:SGRaTrlNYNZr5sTGEQ==,iv:7t1y6ZzjifFtImenm6AFgqhpXdILx/VPl3gJA2f0UwI=,tag:wY8gL7nE7/fzK2pQQuzWUQ==,type:str]
    EXTERNAL_DNS_UNIFI_API_KEY: ENC[AES256_GCM,data:WmLKcGAsEsc13WQvSVP+3M9ubDY9Ao4PEtCyZoW3M9M=,iv:0Pmnl2e1d9ksMOvR/h27yB94aWv74d/jpeX6eo4TAI8=,tag:e3OFexXqY8j3KvuYWiZzpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVk4xaG1CYjFNWEM5c29W
            VWhJS0psRnQzQUk0cVN2cUJ3d282cGRtdUdZCjVCTmp1M2V3S3pxUnR2U2tBbVEw
            WTFzTXU5VDJOTkdMMXlQTzlJWWZyazAKLS0tIG92SXUxaUwwSW51RHlDOWwxMy9K
            N3hDVVJzazh1ZUlWaVNHTDlMa0xjUVUKH/dGTITggigKrqJVLgxex9xikOu1lxof
            pQ8+LM/iCA0cQ8fs7Vga+mK8NoTFSur/IgsSU7WEpqeHhx76SSBuYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T04:26:17Z"
    mac: ENC[AES256_GCM,data:sMQ2/svY9JlvoXfq5jGRtPelbbrlBpFhTiF/UV6Ii/xGE2r6EOQu7ERECyIEB4CplsD4aPDIOZ62R1G8uq7BbDsUWY8FToL96h0hDZyTx4qSJAZbVBdrljEKZldHBAphIAooU0TDmqOjaVGoc4zHX29/v8lvpFGwsa73rOC3VmY=,iv:tF512bcQwioMy8t3d3nk66C6IXNVzxvvehMHYro+kDk=,tag:sNlb5QW/46lio/u3hUjmNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
