apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
stringData:
    UNIFI_HOST: ENC[AES256_GCM,data:SGRaTrlNYNZr5sTGEQ==,iv:7t1y6ZzjifFtImenm6AFgqhpXdILx/VPl3gJA2f0UwI=,tag:wY8gL7nE7/fzK2pQQuzWUQ==,type:str]
    api_key: ENC[AES256_GCM,data:9pYxianQsSvKLiA/xsxOWlycUr1C874J66Scr34IdW0=,iv:mIHPjZnaoQQS9J+quagCrWv+wdieEmVqxv4jDh/66Aw=,tag:KBK4edjzvr2fjuZsgILrFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVk4xaG1CYjFNWEM5c29W
            VWhJS0psRnQzQUk0cVN2cUJ3d282cGRtdUdZCjVCTmp1M2V3S3pxUnR2U2tBbVEw
            WTFzTXU5VDJOTkdMMXlQTzlJWWZyazAKLS0tIG92SXUxaUwwSW51RHlDOWwxMy9K
            N3hDVVJzazh1ZUlWaVNHTDlMa0xjUVUKH/dGTITggigKrqJVLgxex9xikOu1lxof
            pQ8+LM/iCA0cQ8fs7Vga+mK8NoTFSur/IgsSU7WEpqeHhx76SSBuYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T04:31:48Z"
    mac: ENC[AES256_GCM,data:BOCvhXJv2sYzoWHRjV5IxH3RzfCPkg8IlLFzVOEDj6djJJxBejBBlNP++o97ExoR2hN7EyOddP/UvkgqBCIBn2UKl2jX51IRxix/RUXMiL4zuJweRFs2duVjqF3xT0QelQLKTfWsghCBsSq6+GnQqJrVshJF0l/ecvX26ejxRXE=,iv:r/hR9q+pSf6G8QAu5lMC50e4Xo46km/dcw5g3YIEX5E=,tag:XtHT0cV/x2a239Zd8XVhoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
