apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
stringData:
    api-key: ENC[AES256_GCM,data:ax2n42T+8/3fWD9R+VirNXa1H/jAko7pmUDWGh2I+c4=,iv:5VxqnbL7mbLpMkH+H36cgwmQ2OiX1DGa6CDD/iwIJ7A=,tag:DQR1LbZoQtG7itE2fTItcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVk4xaG1CYjFNWEM5c29W
            VWhJS0psRnQzQUk0cVN2cUJ3d282cGRtdUdZCjVCTmp1M2V3S3pxUnR2U2tBbVEw
            WTFzTXU5VDJOTkdMMXlQTzlJWWZyazAKLS0tIG92SXUxaUwwSW51RHlDOWwxMy9K
            N3hDVVJzazh1ZUlWaVNHTDlMa0xjUVUKH/dGTITggigKrqJVLgxex9xikOu1lxof
            pQ8+LM/iCA0cQ8fs7Vga+mK8NoTFSur/IgsSU7WEpqeHhx76SSBuYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-26T17:53:40Z"
    mac: ENC[AES256_GCM,data:DJWaitClBfvcdJMdhhmqUfoGlaw1q7iT+gBkLMTXgURxJMb//yNL+PXo3/X3A4ZtO7+uM6orIOKmT57uh8dyfXig28EZy7zdfagxF2VjX5aNpvxWp0E+zaENMEw9zYe7Z7AXMvMJF5Ve5CvBwYjB1VK/e7oza9CZ39yeQIbmzsQ=,iv:OO0HFBtggc2lPIwuim5UprqZwdnggadYQWhVf6FoGPo=,tag:4BPS2UdJvBIbohNGaO6SDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
