---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./lldap/ks.yaml
  - ./authelia/ks.yaml
  # - ./authentik/ks.yaml
  # - ./crowdsec/ks.yaml
components:
  - ../../components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: security
    target:
      kind: Namespace
