---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app scrypted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controllers:
      scrypted:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-iot",
                "namespace": "network",
                "ips": ["10.0.101.14/24"],
                "mac": "64:16:7f:38:60:01"
              }]
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109

        containers:
          app:
            image:
              repository: ghcr.io/bjw-s-labs/scrypted
              tag: 0.137.0@sha256:8efdd2846735f831c925b49052f00372f8d6de913f72359628bd8e095e11a6f6
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 136m
                memory: 1024Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 8192Mi
            securityContext:
              privileged: true

    service:
      app:
        controller: scrypted
        ports:
          http:
            port: 11080
            primary: true
          rebroadcast1:
            port: 34135
          rebroadcast2:
            port: 34136

    ingress:
      app:
        className: "internal"
        hosts:
          - host: scrypted.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          scrypted:
            app:
              - path: /server/volume
      cache:
        type: emptyDir
        globalMounts:
          - path: /.cache
      cache-npm:
        type: emptyDir
        globalMounts:
          - path: /.npm
      recs:
        type: nfs
        server: shango.internal
        path: /mnt/user/k8s/scrypted
        globalMounts:
          - path: /recs
