apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
stringData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:MjMiZ/WY0wdFBPuRk3JO7qeeg6UgqzYkok3wVv0npQ==,iv:5Phpd89uiY98a3GOj/2Lh5QEWQ6ZuB0SdJ2x3TCXquk=,tag:p8vTZXKHtiN61mjFu5eMqA==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:eu5fh7HBEFuea1Dlr1ZQK+kB4qKqx/ER/io+nYFt8COnxPsJg91V87zOXc3m+NdlZlq05eXvkY8mNw==,iv:XTJkn6EDtsBT3kWO3sgbjICl973z38Gh1yY5nMyk9co=,tag:TfovZLb6s8HaOy4wkXqHOQ==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:yRQPzA==,iv:3BHXBBRzCsysf6fFxAwwivk1WCQWI78OiaTVqmF6XLw=,tag:Ym5iaNgccH5JG+lEx0cJVQ==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:530gqbjtFmJpAbpv,iv:B/ULyUXoBp/lesgspHh4OOb/8dNgeugmQ4Tp4qarkKY=,tag:sqRouIAkQw/+QFwEgiT3FA==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:35REbSsE+YxKE/tf,iv:VaoGqnPDeZ+037y+bhEsaemK9ohRNU00XiiUXaDdlSo=,tag:XocrLEuXPK74w3QXwBdO1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRC9lOC81cGlPNmVmbmxS
            UVAwZlJXTTZKYWVtYlk2NFdHQmNlOWNlNERNCjRQTmNqMnM4N3FjSjJXUUphbjgw
            MllwSmVTTmhFcC9qMUFsbFZjcFdXdmcKLS0tIG9Tclc2RmdiSkdRZDFiemgwWGhQ
            OUdXQmpXN0srNzQ0bHJOMllSZ29aaUkKhOFEVOf5D/3mTAan54kkaOEP17ePqShc
            BB8ocp+N30HgLHLI6A7jaeJ5aBvpcIntN33W1LLLCCguIQA4CW91Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T21:23:44Z"
    mac: ENC[AES256_GCM,data:6UDUfLnnVSoCh0LBCto0vBwkSRq15fynUEd/c8zsDNRFWOKeh9j9gxSrdza4jxmfmLIm2hAVAMjRXePocSAekjQn9e/qpu5EXCvbgn5ikI5ypfeOIbTXrD//Ayx1H/3VlKey3Ta0ikHrUaNYmqXMtfRMZrszoQGoSOEsLD+2jIs=,iv:i/SgEl2BHTPwNrbJc9dw07aIFYhQssvuUxQ+iy/0YWU=,tag:njPH2sdbUZIUgJV5Ou0wrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
