apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-secret
stringData:
  #ENC[AES256_GCM,data:IclJjA93eB3pwl0DsIVFFyIQ00g1zHr3U6xXq01PTrFP8fXxbbiHYnmPrTOu21YKwSk20wgstvbAZ6w3886D6c/3iAazRm4=,iv:n9SuBheaUfRqTSlpzVY4nUwNSlzkAOd4dnFpgyM8gqk=,tag:xoSZJp23JSYh1dPLH1w7zw==,type:comment]
  #ENC[AES256_GCM,data:IX2W5fAb92Ax4H+KgAFjzJsqznzO6anGmbkLaHHtQUwGKHtC/+CHKXyzSSCWPDzJujl/HLDbd40pkCfXAXOKwRWkeLtJrBLTfytp8MmfGGsCT4mkTasxx9vQW1gIT28k,iv:FaYm8yi8J0x8RFYaTvFp0J5GUGGg//I0krBVhMjfvjA=,tag:Q/UkO5t2EuehrU3eWNDRPA==,type:comment]
  #ENC[AES256_GCM,data:UJy/dBTrZ95UcQ7+ExRP2FZ9HISSgeT5gPCc3z22UWQnR6IzHyQleZkfDWk=,iv:d3AlXgvbfWEhbCTGS4WAhlB5Wa2vgCbGowbaNnvNPqQ=,tag:Qw9jNCSx72P7fshan02n0A==,type:comment]
  ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:530gqbjtFmJpAbpv,iv:B/ULyUXoBp/lesgspHh4OOb/8dNgeugmQ4Tp4qarkKY=,tag:sqRouIAkQw/+QFwEgiT3FA==,type:str]
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:35REbSsE+YxKE/tf,iv:VaoGqnPDeZ+037y+bhEsaemK9ohRNU00XiiUXaDdlSo=,tag:XocrLEuXPK74w3QXwBdO1w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRC9lOC81cGlPNmVmbmxS
        UVAwZlJXTTZKYWVtYlk2NFdHQmNlOWNlNERNCjRQTmNqMnM4N3FjSjJXUUphbjgw
        MllwSmVTTmhFcC9qMUFsbFZjcFdXdmcKLS0tIG9Tclc2RmdiSkdRZDFiemgwWGhQ
        OUdXQmpXN0srNzQ0bHJOMllSZ29aaUkKhOFEVOf5D/3mTAan54kkaOEP17ePqShc
        BB8ocp+N30HgLHLI6A7jaeJ5aBvpcIntN33W1LLLCCguIQA4CW91Sg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-14T20:41:16Z"
  mac: ENC[AES256_GCM,data:R8wbXLmObJunHbO2HiWdZ8WYJdAIspF4aOiuV0ABlpFZQk9FHcE2p6x81MXGo6I9XuZsJQjPeUYoSC+CGBuiHEbc9BipDJrmHYd4glfxsrSoDjQwjZ5I4bL7lltl+vjHDyDzz3gKNxeAsa5I32pOm2fxN1SeYtaaAbXCulHx7G4=,iv:94q4NcQcZi5gugrVUVvwl/VE6P0HzHS4/DhvAxsJNfc=,tag:sbg/2bnt6YX7CE8y2L0t0Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
