apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:XoOBh5I8ZXUWMVXqzzG6c+uSXnY99MeFCr8ufE+x0ke8pIF4MePf746YYbaEZgoHCMyZF/EkgRsCd/hcwbQZ5Hf92gUdhNDxbrx5,iv:kRIdsK2jjuFtZBtA0Kxpi+zj/g4CdDu5pAZy3HfW988=,tag:oV17H7bPwOkhQVAA/cXffw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSUdCL1J2VmJ6U05aU3Qy
        S3AxVk9NS0R3ejBURXB5YWxqOEhzbElwalVjCmh0Ykl5c3VhNXhYS0N5OXYxUHU3
        V1VmeEtDQ2M3SHdzYnVScXFpUi9ONzAKLS0tIE1ycGM0cDZSNFJWaUpBVm9YYmlF
        emNuamlvL0c5QlJYdzhQNDBrYk8zaWcK6zWDxkTNwZ2fygiZl31wxMQ891zVmgZe
        rVQhS7xu6R1AiQEQTtHtjKOzsTezr1tXach/g+nx63oIB/5V/aYK6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-24T00:26:16Z"
  mac: ENC[AES256_GCM,data:y9BMBqLNCPu/aQIPEtwYK6C5p0M/xnZ1RYM7QXowo9dtISIdK6ruT8Bb1Zs6ONuDZztVmYbkadrdt4LCp5t4iJc6vGh50lsj04mmHKJYHC5PFptl/eolUd1CFreNM5Q2hjiCfqy6D16Az0Jlj43UAHq1sFu4J8RtiB6EdiBgjqE=,iv:GjB4mhMe1sm8iMmy8kDOPGd7eN4hd962zIrV3+ejzQw=,tag:R2FQurZ1D9GoVKAAM4ICKg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
