apiVersion: v1
kind: Secret
metadata:
  name: slack-secrets
stringData:
  address: ENC[AES256_GCM,data:CtKZfO1uFJjBo4cfG6RgZ4eWLHKfTRNv4xxOHRuu+k7qLPZpN6L0ExMj9HB4IaRkSBrNl3gp0uqkAsK/7ztJZpFTb1YVqyb9qdNzqXAabxUn,iv:bzQMvQ+GQeD3tAogbTPiZhASqSvxR/4EfHudxwIyvaY=,tag:Gc1PPZy0XFyviVsnj/K0nw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYlV5QnhnczE4ejM0QU44
        NzJxK25XcFFjWHhCeVJqZ3o1ZmxGNis0QTFZCldwZlMxWXhmMkpTM0xnMmo0YjBB
        MHI1QkUvZTNFNVpwOXBmVDNPQUZwSlkKLS0tIHRoa1RONEw3Q2ozek9CTTNTUlhB
        VEs1N0dLNmNwR0J2MVpXV3lNWmJNclEKcVgnHrSjyAEDFsnxo3RByr87oyNMZ5en
        bzzj2eJkIivwlm9ghAwEGr0s1g8Eipp1/3tksjpmsqYV+K0Ym6QlFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-14T09:45:45Z"
  mac: ENC[AES256_GCM,data:pU9jX7kVapr4Bl690jMWsnGAe2ScaiyhJhgDamR2ICebqtnjTTUHtLtV80vNOML4Qys+whNjNBsXaRDuNGbgkmfPGphVGUM+aUqW8NS5eAOx3x046XvTrWWme2JGAH7gOIhlTAjoBhA6VvvJIaZWqRGcnc9pDyd1WzvF3/lCQaY=,iv:xNGcHpkaYT3HVOzha9EccAJjPlynfLrraJxROTQDxPY=,tag:wfw2I91/fK5Nvl/Jo80Xeg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
