---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: &namespace home
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/apps/home/home-assistant/app
  components:
    - ../../../../flux/components/volume
  dependsOn:
    - name: multus-networks
      namespace: network
    - name: longhorn
      namespace: storage
    - name: emqx-cluster
      namespace: dbms
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
  postBuild:
    substitute:
      APP: *app
      APP_UID: "0"
      APP_GID: "0"
      CAPACITY: 5Gi
