apiVersion: v1
kind: Secret
metadata:
    name: adguard-sync-secret
stringData:
    #ENC[AES256_GCM,data:Np9WnKqbRXMnRw==,iv:tlvoSubJJVf1yn3PZ+buKw6VmoOJS/rXhWwtlcM7fVU=,tag:klNFmFAwsiEKlkOlsBfSJw==,type:comment]
    ORIGIN_URL: ENC[AES256_GCM,data:cR/+XKoUlqqFPsDHf1W4HJXXBkCf7w==,iv:9VjfTstSjySt50KYaE5Z+7PHpUJkXafyu8JI/LNEZLs=,tag:x46K1jBZyyN1eXMEkKFxug==,type:str]
    ORIGIN_USERNAME: ENC[AES256_GCM,data:JatNvjTg3ptIdw==,iv:Jgty/1u746+N3Bw1CpX3KNURmsQ7jPT1LCBr8geNi34=,tag:JMQBZghiHCXlzVBAlnRpLQ==,type:str]
    ORIGIN_PASSWORD: ENC[AES256_GCM,data:NDA/D30eYsjOXFyfj1965Q5QwlI+ATZTNMl/SoYZMT7FxZMPKcASQE/ZJw==,iv:9Zlp5MiGTERIP6Dhjrkdo7pQxPLoOLvmQ2ft59yfz78=,tag:kOIiAL+xqGj8N0QNu6TZSQ==,type:str]
    REPLICA1_URL: ENC[AES256_GCM,data:6baCX5aH0+DgPtX6QJMqXQ==,iv:vUYjfE+1IqV8roZFnkOLARmAIa/Rpo9vJI4E3FIdrbY=,tag:WtjBaSJO0EJTk+ZK/84JRw==,type:str]
    REPLICA1_USERNAME: ENC[AES256_GCM,data:lOi5Yn46A4CSrw==,iv:AxxiE/jZCzzsDLgceQ5QDEtXsjHZSAoJ5TiuhE+PcOU=,tag:KHJordmf5FVBHM94JaKtwA==,type:str]
    REPLICA1_PASSWORD: ENC[AES256_GCM,data:pWBPyR3HkPMJGsyrDiEr/morVgprLkUclamy+5NsWAr8difM2uVSJ3ZHNA==,iv:A+DgeYNpLFQHAhFfPfk25fiWtNm85VZeFiJ05ev5ATk=,tag:9mGRlblwXoyHkLpozqXICg==,type:str]
    REPLICA2_URL: ENC[AES256_GCM,data:Kq8vZYHyjo6FwvgaVqv6DA==,iv:8ECeqPPj4iVX50ZaJkSyVkUvpE7q5u+5eBxBQh0eDIc=,tag:d2cC02IwVOpc1P1gVblnkA==,type:str]
    REPLICA2_USERNAME: ENC[AES256_GCM,data:BnmAgkCHKfP5tA==,iv:0uybu/HlBcVQhQc/Utrrbu6hpJHgsZ0PwhQR+dI0MKI=,tag:F4hdLm/4TOCk//z6fb/Jlg==,type:str]
    REPLICA2_PASSWORD: ENC[AES256_GCM,data:FRylhOUstMQGXA6iIbh/3vJEvOc137POnlhg+gY8rfWU9R5Z3lA9bu0/xA==,iv:UkSyaR2TBNIlkFUUVLxuFgDkG6pAjYRXpGqb0kGm8l4=,tag:d6ZFJkbbJF+U+g2lDq3LGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza2FRcEtoMVNCelJZK3ZC
            Tm9nT2JvU0dPSDcxOGxmRXUxY0hPb0NQUDE0CkJLTnRMS3dkRUx3UXhsVG9GZ0lo
            ZUZUVHBHVGNxUnNDaFpGSzNsWjBxUmMKLS0tIEZLNU44QlJJZmg5ZUVyRlFzOHFi
            R1EvM1diaWJjZWtiQjJxWFBUNE02T1UKPn/OG0a27rYh/otxheUK8RVWuU0ije/7
            ktdSvBSfVBxmri63Koz630zDrqGbW9auiv4wHTZpqjDAB/yNs20uaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-12T05:36:33Z"
    mac: ENC[AES256_GCM,data:s/9fKEn5teQg1v4MezWHuskmcUUkSde2pu2pq7qWqCvgFGQaJlrVcHTfNS1guR8QdLaWWBVfoRftZCUKWq0wUIDAYqF6lWE9zWjqkbNbZZHWU1CbMB73pX+qdPt0YzejQaOA/QuSkS1XnEPN2NmLgBnS2qDfN3+yQ4Mt55eqKpE=,iv:/X0tcwr6v34CFUL+SA0RRkEIXpUUgwRv1Hac7GXSRxQ=,tag:/KSX5yZ4uCseVrMaHianIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
