apiVersion: v1
kind: Secret
metadata:
    name: adguard-sync-secret
stringData:
    #ENC[AES256_GCM,data:Np9WnKqbRXMnRw==,iv:tlvoSubJJVf1yn3PZ+buKw6VmoOJS/rXhWwtlcM7fVU=,tag:klNFmFAwsiEKlkOlsBfSJw==,type:comment]
    ORIGIN_URL: ENC[AES256_GCM,data:TH6UEldUOcxASKqbZGoqMxSMNWV9jFoYgDYW8ds=,iv:mqkbWqkdBbcea2MoIUNSY7skNmhAUtT73fBmKHCUm8g=,tag:MdU6s9t7LnxB5/YI0REJjw==,type:str]
    ORIGIN_USERNAME: ENC[AES256_GCM,data:JatNvjTg3ptIdw==,iv:Jgty/1u746+N3Bw1CpX3KNURmsQ7jPT1LCBr8geNi34=,tag:JMQBZghiHCXlzVBAlnRpLQ==,type:str]
    ORIGIN_PASSWORD: ENC[AES256_GCM,data:NDA/D30eYsjOXFyfj1965Q5QwlI+ATZTNMl/SoYZMT7FxZMPKcASQE/ZJw==,iv:9Zlp5MiGTERIP6Dhjrkdo7pQxPLoOLvmQ2ft59yfz78=,tag:kOIiAL+xqGj8N0QNu6TZSQ==,type:str]
    REPLICA1_URL: ENC[AES256_GCM,data:e/7zHB/HZ+p8lXfxF7tRKckXYsFmRkoXYA07ZSt3sg==,iv:X9nNGwA/Qp1wI2H/DNMHeym9v+5ytXapdxFvEXSfSwE=,tag:mz1n6sLmHeAJxtcnbwVdxw==,type:str]
    REPLICA1_USERNAME: ENC[AES256_GCM,data:lOi5Yn46A4CSrw==,iv:AxxiE/jZCzzsDLgceQ5QDEtXsjHZSAoJ5TiuhE+PcOU=,tag:KHJordmf5FVBHM94JaKtwA==,type:str]
    REPLICA1_PASSWORD: ENC[AES256_GCM,data:pWBPyR3HkPMJGsyrDiEr/morVgprLkUclamy+5NsWAr8difM2uVSJ3ZHNA==,iv:A+DgeYNpLFQHAhFfPfk25fiWtNm85VZeFiJ05ev5ATk=,tag:9mGRlblwXoyHkLpozqXICg==,type:str]
    #ENC[AES256_GCM,data:kpYtZu28xsZ3R4wqWCSm3XNb0hD+WV4McD4aZn7OkfhDOlslIOGBiw==,iv:BvuU3xQ0bBpcio/hLPj39Wuyuhf4RHV4kxW1vZffr8c=,tag:uGGNRx21dhlFhBU7RzXAog==,type:comment]
    #ENC[AES256_GCM,data:0nQ9mrtKzPPMDmWX9H7q0bUYIcDpqiblsjt7sYM+,iv:ZNQ4ZIwdx+LzCdX16dQXxTkuFJc4gnZXwo9YfjvnLvw=,tag:7sv2hireB8E3wxmS2spkjg==,type:comment]
    #ENC[AES256_GCM,data:vbxLlyPk1+9u5sJvCmJPY4a2fh64JL8jXGIKnZe0JYuTXcH4n1m+es9k7o3h7lKU4yqmZMvo4c3UMmTAqjft,iv:PpcK3S1s/xyjnDj1CWE/yH8AE6wLxzla4GYuhymMbQM=,tag:wpzNMRxXVOcDaEYPJH0nSw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza2FRcEtoMVNCelJZK3ZC
            Tm9nT2JvU0dPSDcxOGxmRXUxY0hPb0NQUDE0CkJLTnRMS3dkRUx3UXhsVG9GZ0lo
            ZUZUVHBHVGNxUnNDaFpGSzNsWjBxUmMKLS0tIEZLNU44QlJJZmg5ZUVyRlFzOHFi
            R1EvM1diaWJjZWtiQjJxWFBUNE02T1UKPn/OG0a27rYh/otxheUK8RVWuU0ije/7
            ktdSvBSfVBxmri63Koz630zDrqGbW9auiv4wHTZpqjDAB/yNs20uaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-20T17:01:07Z"
    mac: ENC[AES256_GCM,data:a39lCBOOPpPmKvhtfyeJ94JmpVQaHmWk2ZKVe75cOVdjOOgj/QTBJ5EGszW12HI5kd5CD/Pxnqh1AmnW+zMMc3NOR6iL+y96EKFPBqY9t5bE+3Z0pkzgXnFB9/fgFSWJB6y3OGSKSDuQopYhDuro+GzBBGjHsJe0YgIaOiQqBmk=,iv:kAJjLn9IFalMavgqlIJ9UFLAL8d25zxbTOfDHy5bkTI=,tag:NfpxRBY2PU5QLGVeSH1eCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
