---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app orbital-sync
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      orbital-sync:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          # annotations:
          #   k8s.v1.cni.cncf.io/networks: |
          #     [{
          #       "name":"multus-mgmt",
          #       "namespace": "kube-system",
          #       "ips": ["10.90.1.13/24"],
          #       "mac": "64:16:7f:cf:86:4f"
          #     }]
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: mattwebbio/orbital-sync
              tag: 1.8.4
            envFrom:
              - secretRef:
                  name: orbital-sync-secret
            resources:
              requests:
                memory: 250Mi
                cpu: 50m
              limits:
                memory: 500Mi
