apiVersion: v1
kind: Secret
metadata:
  name: orbital-sync-secret
stringData:
  #ENC[AES256_GCM,data:Np9WnKqbRXMnRw==,iv:tlvoSubJJVf1yn3PZ+buKw6VmoOJS/rXhWwtlcM7fVU=,tag:klNFmFAwsiEKlkOlsBfSJw==,type:comment]
  PRIMARY_HOST_BASE_URL: ENC[AES256_GCM,data:m1vpr14XlD3LeO6+BeZRnzE=,iv:XImEipwteyYYg7m9q/bImDzv9Pc8f5GT3BuRFC9mmJs=,tag:rxqazzcDLTTLb5nnvqjevg==,type:str]
  PRIMARY_HOST_PASSWORD: ENC[AES256_GCM,data:AOngVMjh5Yk=,iv:pSR3ssAiAB62lyhOueCMwyVyV2wOZ8lOPoaZSIbx18Y=,tag:UkOdXWzGZLn/3gwe+vpEwg==,type:str]
  SECONDARY_HOST_1_BASE_URL: ENC[AES256_GCM,data:E72gPlgO90NEqrQuMS+Nx3g=,iv:IqVLQ6T7ITTFq5hYJJhX35wSUEdeP0XFeYkBA274ywA=,tag:i/L9nOE0aXTjujC7GJFDFg==,type:str]
  SECONDARY_HOST_1_PASSWORD: ENC[AES256_GCM,data:Kh5U5bpexiQ=,iv:eNSNO50PaU5gQ+kO+mzxvvzqPmVaBa7cOWgxi5V09/Q=,tag:ejeIN0gQb1LrUlGKQXoDcA==,type:str]
  INTERVAL_MINUTES: ENC[AES256_GCM,data:GxE=,iv:3BOj+E8+Jcykkb69QKG7iO/5FSZujQvHpTu9yvwiPF8=,tag:I/9uUhpTnVw1urEscSAXdw==,type:str]
  #ENC[AES256_GCM,data:EN4PtLM=,iv:quLbW8Qx4m1KTy8nn15mcc+sIeqClNC39cOd6tO//1w=,tag:OwgYkXxbHO75suaqM8+0bA==,type:comment]
  NOTIFY_SMTP_ENABLED: ENC[AES256_GCM,data:i2JHzQ==,iv:QdoEGHzfVy+VGYnT9UcRdd3eyIBLRTDwaZnaR1Wh6pU=,tag:QvVwJzzFF+k1zapRlG2R+A==,type:str]
  NOTIFY_SMTP_FROM: ENC[AES256_GCM,data:Tnn7ScYl6FqpaX8KMxfyoDVF0nDeNHlP2pUbWTZqAXM/fg==,iv:NcMKI2foRdn/hEgkzgFvRKE5QHvGVY7sRL/bjuViN54=,tag:tRo5pOnYOhLz9cnrgPfozA==,type:str]
  NOTIFY_SMTP_TO: ENC[AES256_GCM,data:icGQcJMFFJk1IsZCvO2yyQ==,iv:ya4ya3Z7xgstarjbW5TBDJzzBjyzLlbsBktJcyzgWec=,tag:pCLatFXyFIfM3ZlxDoBkig==,type:str]
  NOTIFY_SMTP_HOST: ENC[AES256_GCM,data:n0rqYq+BZtqlkQMb5ssX3NARlYE0pQ==,iv:kFKxc/zVObSibf+asxVONSCldNCCZCgpA62RcXmmuy4=,tag:30i41TcIogmccM7h6avPcw==,type:str]
  NOTIFY_SMTP_PORT: ENC[AES256_GCM,data:DxE+,iv:xaczM5STncFd6crnhSSxMWkMZeBe6ztEuOo7eb3C3Zo=,tag:EE1qWCN98H3nIex9UrpdrQ==,type:str]
  NOTIFY_SMTP_TLS: ENC[AES256_GCM,data:RBBY3g==,iv:2Ipa24Isjl5PoxQ/1KtwGhthrN5yOni8mWX/jbg3kd0=,tag:+uyIjZYi2dw8LyxUq5qrUw==,type:str]
  NOTIFY_SMTP_USER: ENC[AES256_GCM,data:2L/j4kLNqN5mn9p1NKXLzaXB3ZooOGg=,iv:NmiEtBvD2WbLKZ5R45Mng7CHP+gG2W0HYbEP+pzfNVk=,tag:dw27b/kXXHZOt4Ymcg7WBQ==,type:str]
  NOTIFY_SMTP_PASSWORD: ENC[AES256_GCM,data:VOlNzg/3F5PRI0NllgtwCJbbLwzz6a8=,iv:ltz7h5uiRKyo+RmsXxDUAHLaD26wHaiDLZEdBphAhrA=,tag:4k8vnrKKujWLcBOXmCaIYw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qxapmx8jckngwyt8gpgk4lkt3w0e2vame3lcgs5cflgrpdalnu0qvp59zz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza2FRcEtoMVNCelJZK3ZC
        Tm9nT2JvU0dPSDcxOGxmRXUxY0hPb0NQUDE0CkJLTnRMS3dkRUx3UXhsVG9GZ0lo
        ZUZUVHBHVGNxUnNDaFpGSzNsWjBxUmMKLS0tIEZLNU44QlJJZmg5ZUVyRlFzOHFi
        R1EvM1diaWJjZWtiQjJxWFBUNE02T1UKPn/OG0a27rYh/otxheUK8RVWuU0ije/7
        ktdSvBSfVBxmri63Koz630zDrqGbW9auiv4wHTZpqjDAB/yNs20uaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-14T20:12:19Z"
  mac: ENC[AES256_GCM,data:xR9Klmmq+aDG0Q7GsOXc64bywzqzbk0r3ddLEEH1zVW5rQ9Otw62QF0adA2vVY16LBnKWKaWiE+J2ekFCFRsKGqe32WM0+ASW4hzIm71iok/ixz1XF8OrOWPro+1IYnFkgk8ckOWbLoVcJIGqHUCsMh8eUiEweCWeXMxjfwcYhM=,iv:pbId3Gi6u18h1fVkgWByD2aZOpU8sT3K1L2WKJViJGk=,tag:JYFDDsC6/I2MBBwTqini0Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
